import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import Ajv2020 from 'ajv/dist/2020.js';
import { planExecutive, operations } from '../skills/woia-executive/scripts/executive-plan.mjs';
const valid = operation => ({operation,organization:'org',scope:'portfolio',actor:'manager',target:'direction-1',source_revision:'rev-1',correlation:'request-1',evaluated_at:100,current_grant_revision:'grant-1',evidence:{owner:'competent-owner',source:'accepted-record',revision:'rev-1',accepted:true,fresh:true,conflict:false},grant:{actor:'manager',organization:'org',scope:'portfolio',target:'direction-1',source_revision:'rev-1',operation,competent:true,revoked:false,revision:'grant-1',valid_from:90,valid_until:110}});
for (const operation of ['direction','exception']) test(`${operation} produces no effects`,()=>assert.deepEqual(planExecutive(valid(operation)).effects,[]));
for(const key of ['actor','organization','scope','operation','target','source_revision']) test(`reject mismatched grant ${key}`,()=>{const input=valid('direction');input.grant[key]='other';assert.equal(planExecutive(input).result,'BLOCKED_AUTHORITY');});
for(const key of ['competent','revoked']) test(`reject ${key} guard`,()=>{const input=valid('direction');input.grant[key]=key==='revoked';assert.equal(planExecutive(input).result,'BLOCKED_AUTHORITY');});
for(const key of ['accepted','fresh','conflict','revision']) test(`unknown evidence ${key}`,()=>{const input=valid('direction');input.evidence[key]=key==='revision'?'stale':key==='conflict';assert.equal(planExecutive(input).result,'UNKNOWN');});
for(const op of ['external.send','payment.execute','scheduling.create','receiver.task.update','kpi.redefine']) test(`unsupported ${op}`,()=>assert.throws(()=>planExecutive(valid(op))));
test('hierarchy and urgency cannot supply grant',()=>{const input=valid('exception');delete input.grant;input.priority='urgent';input.title='CEO';assert.equal(planExecutive(input).result,'BLOCKED_AUTHORITY');});
const indicator=()=>({owner:'finance',definition:'accepted-definition',period:'2026-10',population:'approved-population',source:'finance-summary',scope:'portfolio',fresh:true,value:0,limitation:'scope limited'});
test('observed zero retained without causal claim',()=>{const input=valid('view');input.indicators=[indicator()];const output=planExecutive(input);assert.equal(output.indicators[0].value,0);assert.equal(output.causal_claim,false);});
test('missing measurement never zero',()=>{const input=valid('view');input.indicators=[indicator()];delete input.indicators[0].value;assert.equal(planExecutive(input).result,'UNKNOWN');});
test('incomparable periods are not combined',()=>{const input=valid('view');input.indicators=[indicator(),{...indicator(),period:'2025-10'}];assert.equal(planExecutive(input).comparable,false);});
test('cross-scope measurements rejected',()=>{const input=valid('view');input.indicators=[{...indicator(),scope:'private'}];assert.equal(planExecutive(input).result,'UNKNOWN');});
test('receiver owns contribution and acceptance is distinct',()=>{const input={...valid('contribution'),receiver:'finance',outcome:'scoped summary',decision_version:'rev-1'};const output=planExecutive(input);assert.equal(output.receiver_task_owned,true);assert.equal(output.acceptance,'NOT_YET_ACCEPTED');assert.equal(output.completion,'NOT_RUN');});
test('contribution decision revision must match accepted source',()=>assert.equal(planExecutive({...valid('contribution'),receiver:'finance',outcome:'scoped summary',decision_version:'other-revision'}).result,'REVALIDATE'));
test('changed premises revalidate despite pinned grant',()=>assert.equal(planExecutive({...valid('follow-up'),premises_changed:true}).result,'REVALIDATE'));
test('satisfaction without owned residuals stays open',()=>assert.equal(planExecutive({...valid('follow-up'),premises_changed:false,outcome_state:'satisfied',residuals_owned:false}).result,'CONTINUE_OWNED'));
test('close only satisfied scoped outcome',()=>assert.equal(planExecutive({...valid('follow-up'),premises_changed:false,outcome_state:'satisfied',residuals_owned:true}).result,'CLOSE_EXECUTIVE_OUTCOME'));
test('input not mutated',()=>{const input=valid('direction');const copy=structuredClone(input);planExecutive(input);assert.deepEqual(input,copy);});
test('five methodology phases retained',()=>assert.equal(operations.length,5));
for(const instant of [89,110,111,NaN]) test(`reject out-of-window grant ${instant}`,()=>assert.equal(planExecutive({...valid('direction'),evaluated_at:instant}).result,'BLOCKED_AUTHORITY'));
test('reject stale grant revision',()=>assert.equal(planExecutive({...valid('direction'),current_grant_revision:'grant-2'}).result,'BLOCKED_AUTHORITY'));
test('missing grant interval fails closed',()=>{const input=valid('direction');delete input.grant.valid_until;assert.equal(planExecutive(input).result,'BLOCKED_AUTHORITY');});
test('request schema validates complete envelope and rejects missing scope',async()=>{const schema=JSON.parse(await readFile(new URL('../skills/woia-executive/references/request.schema.json',import.meta.url),'utf8'));const validate=new Ajv2020().compile(schema);assert.equal(validate(valid('direction')),true);const missing=valid('direction');delete missing.scope;assert.equal(validate(missing),false);});
test('manifest binds Core hard minimum version',async()=>{const manifest=JSON.parse(await readFile(new URL('../dev.woia/manifest.json',import.meta.url),'utf8'));assert.equal(manifest.schema,'dev.woia.department-orchestrator/v1');assert.deepEqual(manifest.requires_plugins,[{name:'woia-core',minimum_version:'0.5.3'}]);});
